
# Gem::Specification for Gem_leaves-1.0.3
# Originally generated by Echoe

--- !ruby/object:Gem::Specification 
name: gem_leaves
version: !ruby/object:Gem::Version 
  version: 1.0.3
platform: ruby
authors: 
- Gufo Pelato
autorequire: 
bindir: bin

date: 2008-08-15 00:00:00 +02:00
default_executable: 
dependencies: []

description: A dumb tool to list removable gems.
email: ""
executables: 
- gem_leaves
extensions: []

extra_rdoc_files: 
- lib/gem_leaves.rb
- bin/gem_leaves
- README.txt
files: 
- lib/gem_leaves.rb
- bin/gem_leaves
- History.txt
- README.txt
- Manifest.txt
- gem_leaves.gemspec
- Rakefile
has_rdoc: true
homepage: ""
post_install_message: 
rdoc_options: 
- --line-numbers
- --inline-source
- --title
- Gem_leaves
- --main
- README.txt
require_paths: 
- lib
required_ruby_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - ">="
    - !ruby/object:Gem::Version 
      version: "0"
  version: 
required_rubygems_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - "="
    - !ruby/object:Gem::Version 
      version: "1.2"
  version: 
requirements: []

rubyforge_project: 
rubygems_version: 1.2.0
specification_version: 2
summary: A dumb tool to list removable gems.
test_files: []
